### ISSUE TITLE
Allow customized zoom

### ISSUE THREAD

**Issue by andreprawira** [vernak2539/chrome-extension-google-doc-default-zoom#31]
It is already a great tool but it would even be better if we can have a feature that allows customized zoom. Right now there are only 7 % choices, and in my case 67% zoom in is the best to view my sheets, im sure other have their own % level that fits their needs.

**Comment by vernak2539** [comment]
Hey @andreprawira! I've actually created an "extended" version of the extension that allows for this. You can find it [here](https://chrome.google.com/webstore/detail/google-workspace-zoom-def/mdgikencgfhineaememjagpkiclbdkka).

I wrote about why I created a separate extension [here](https://words.byvernacchia.com/blog/2023/06/google-workspace-zoom-default-extended/).
