### ISSUE TITLE
Add Locale Information for RU locale

### ISSUE THREAD

**Issue by oshliaer** [vernak2539/chrome-extension-google-doc-default-zoom#32]
## Localisation Request

- [x] Update existing translation
- [x] Add support for new locale

## Locale

**What locale are you looking to update or add?**

RU

### Image for Context

![](./img-localisation-context.png)

#### Chrome Extension Title

**English:** "Google Workspace Zoom Default"
**New Translation:** "Google Workspace - Масштаб по умолчанию"

#### Chrome Web Store Description

**English:** "Set the default zoom of your Google Workspace application when first loading it."
**New Translation:** "Устанавливает уровень масштаба по умолчанию для вашего приложения Google Workspace при его первой загрузке."

#### Description in Chrome Extension Popup (_purple_)

**English:** "Select the zoom level you'd like your Google Workspace Applications to use when they first load."
**New Translation:** "Выберите уровень масштаба, который вы хотите использовать в приложениях Google Workspace при их первой загрузке."

#### "Applications" Header in Popup (_red dotted_)

Note: "Applications" refers to the Google Workspace applications such as "Google Docs" or "Google Sheets"

**English:** "Applications"
**New Translation:** "Приложения"

**Comment by vernak2539** [comment]
Thanks! I'm away at the moment and will have a look in the next few weeks (hopefully sooner)

**Comment by vernak2539** [comment]
implemented via #33
